// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwopbrnbrbaeljbgwikt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3b3Bicm5icmJhZWxqYmd3aWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODE4MTIsImV4cCI6MjA2NjE1NzgxMn0.hFUZqpQReI5VcRF-jcDz2nuLVnMRGqjiHLS0gvM5uIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
